const Discord = require ('discord.js');
const bot = new Discord.Client();
const TOKEN = ('NTI1NDY2NTI1MzkwNDcxMTg4.Dv3aAQ.SC-kzw01QIFi6pCpBVYaIN54H58')



bot.on('ready', function(){

    console.log("Ready!");
})


function randomMessage(){
    var randomNumber = Math.round(Math.random()*200); 
    switch(randomNumber){
case 0: return	'“Tweeting.”'
case 0: return	'72 virgins.'
case 1: return	'8 oz. of sweet Mexican black-tar heroin.'
case 2: return	'A 55-gallon drum of lube.'
case 3: return	'A bag of magic beans.'
case 4: return	'A balanced breakfast.'
case 5: return	'A beached whale.'
case 6: return	'A big black dick.'
case 7: return	'A big hoopla about nothing.'
case 8: return	'"A bigger, blacker dick."'
case 9: return	'A bleached asshole.'
case 10: return	'A bloody pacifier.'
case 11: return	'A Bop It.'
case 12: return	'A brain tumor.'
case 13: return	'A Burmese tiger pit.'
case 14: return	'A can of whoop-ass.'
case 15: return	'A Christmas stocking full of coleslaw.'
case 16: return	'A clandestine butt scratch.'
case 17: return	'A cooler full of organs.'
case 18: return	'A crappy little hand.'
case 19: return	'A death ray.'
case 20: return	'A defective condom.'
case 21: return	'A disappointing birthday party.'
case 22: return	'A dollop of sour cream.'
case 23: return	'A drive-by shooting.'
case 24: return	'A falcon with a cap on its head.'
case 25: return	'A fetus.'
case 26: return	'A foul mouth.'
case 27: return	'A gassy antelope.'
case 28: return	'A gentle caress of the inner thigh.'
case 29: return	'A good sniff.'
case 30: return	'A homoerotic volleyball montage.'
case 31: return	'A hot mess.'
case 32: return	'A Hungry-Man Frozen Christmas Dinner for One.'
case 33: return	'A lifetime of sadness.'
case 34: return	'A look-see.'
case 35: return	'A low standard of living.'
case 36: return	'A magic hippie love cloud.'
case 37: return	'A man in yoga pants with a ponytail and feather earrings.'
case 38: return	'A mating display.'
case 39: return	'A micropenis.'
case 40: return	'A middle-aged man on roller skates.'
case 41: return	'A mime having a stroke.'
case 42: return	'A monkey smoking a cigar.'
case 43: return	'A mopey zoo lion.'
case 44: return	'A murder most foul.'
case 45: return	'A nuanced critique.'
case 46: return	'A passionate Latino lover.'
case 47: return	'A pinata full of scorpions.'
case 48: return	'A really cool hat.'
case 49: return	'A rival dojo'
case 50: return	'A robust mongoloid.'
case 51: return	'A sad fat dragon with no friends.'
case 52: return	'A sad handjob.'
case 53: return	'A salty surprise.'
case 54: return	'A sassy black woman.'
case 55: return	'A sausage festival.'
case 56: return	'A sea of troubles.'
case 57: return	'A slightly shittier parallel universe.'
case 58: return	'A snapping turtle biting the tip of your penis.'
case 59: return	'A soulful rendition of “Ol’ Man River.”'
case 60: return	'A squadron of moles wearing aviator goggles.'
case 61: return	'A stray pube.'
case 62: return	'A Super Soaker full of cat pee.'
case 63: return	'"A sweaty, panting leather daddy."'
case 64: return	'A sweet spaceship.'
case 65: return	'A thermonuclear detonation.'
case 66: return	'A tiny horse.'
case 67: return	'A toxic family environment.'
case 68: return	'A visually arresting turtleneck.'
case 69: return	'A web of lies.'
case 70: return	'A windmill full of corpses.'
case 71: return	'A woman scorned.'
case 72: return	'A zesty breakfast burrito.'
case 73: return	'La Croix.'
case 74: return	'Active listening.'
case 75: return	'Actually taking candy from a baby.'
case 76: return	'Adderall.'
case 77: return	'African children.'
case 78: return	'Agriculture.'
case 79: return	'AIDS.'
case 80: return	'Alcoholism.'
case 81: return	'All of this blood.'
case 82: return	'All-you-can-eat shrimp for $4.99.'
case 83: return	'Altar boys.'
case 84: return	'American Gladiators.'
case 85: return	'Amputees.'
case 86: return	'An army of skeletons.'
case 87: return	'An asymmetric boob job.'
case 88: return	'An erection that lasts more than four hours.'
case 89: return	'An ether-soaked rag.'
case 90: return	'An honest cop with nothing left to lose.'
case 91: return	'An icepick lobotomy.'
case 92: return	'An M. Night Shyamalan plot twist.'
case 93: return	'An Oedipus complex.'
case 94: return	'An unhinged ferris wheel rolling toward the sea.'
case 95: return	'Anal beads.'
case 96: return	'Another goddamn vampire movie.'
case 97: return	'Another shitty year.'
case 98: return	'Another shot of morphine.'
case 99: return	'Apologizing.'
case 100: return	'Appreciative snapping.'
case 101: return	'Arnold Schwarzenegger.'
case 102: return	'Asians who aren’t good at math.'
case 103: return	'Assless chaps.'
case 104: return	'Attitude.'
case 105: return	'Auschwitz.'
case 106: return	'Authentic Mexican cuisine.'
case 107: return	'Autocannibalism.'
case 108: return	'AXE body spray.'
case 109: return	'Balls.'
case 110: return	'Barack Obama.'
case 111: return	'Basic human decency.'
case 112: return	'BATMAN!!!'
case 113: return	'Beating your wives.'
case 114: return	'Beefin’ over turf.'
case 115: return	'Bees?'
case 116: return	'Being a bust adult with many important things to do.'
case 117: return	'Being a dick to children.'
case 118: return	'Being a dinosaur.'
case 119: return	'Being a motherfucking sorcerer.'
case 120: return	'Being awesome at sex.'
case 121: return	'Being fabulous.'
case 122: return	'Being marginalized.'
case 123: return	'Being on fire.'
case 124: return	'Being rich.'
case 125: return	'Bill Nye the Science Guy.'
case 126: return	'Bingeing and purging.'
case 127: return	'Bitches.'
case 128: return	'Black people.'
case 129: return	'Bling.'
case 130: return	'Booby-trapping the house to foil burglars.'
case 131: return	'Boogers.'
case 132: return	'Boris the Soviet Love Hammer.'
case 133: return	'Bosnian chicken farmers.'
case 134: return	'Breaking out into song and dance.'
case 135: return	'Britney Spears at 55.'
case 136: return	'Bullshit.'
case 137: return	'Cards Against Humanity.'
case 138: return	'Carnies.'
case 139: return	'Catapults.'
case 140: return	'Catastrophic Urethral Trauma.'
case 141: return	'Centaurs.'
case 142: return	'Chainsaws for hands.'
case 143: return	'Charisma.'
case 144: return	'Cheating in the Special Olympics.'
case 145: return	'Child abuse.'
case 146: return	'Child beauty pageants.'
case 147: return	'Children on leashes.'
case 148: return	'Chivalry.'
case 149: return	'Christopher Walken.'
case 150: return	'Civilian casualties.'
case 151: return	'Clams.'
case 152: return	'Classist Undertones.'
case 153: return	'Clearing a bloody path through Walmart with a scimitar.'
case 154: return	'Coat hanger abortions.'
case 155: return	'Cockfights.'
case 156: return	'College.'
case 157: return	'Concealing a boner.'
case 158: return	'Consultants.'
case 159: return	'Copping a feel.'
case 160: return	'Coughing into a vagina.'
case 161: return	'Count Chocula.'
case 162: return	'Crippling debt.'
case 163: return	'Crystal meth.'
case 164: return	'Cuddling.'
case 165: return	'Customer service representatives.'
case 166: return	'Cybernetic enhancements.'
case 167: return	'Daddy issues.'
case 168: return	'Daddy’s belt.'
case 169: return	'Dancing with a broom.'
case 170: return	'Darth Vader.'
case 171: return	'Date rape.'
case 172: return	'Dead babies.'
case 173: return	'Dead parents.'
case 174: return	'Death by Glamor.'
case 175: return	'Deflowering the princess.'
case 176: return	'Dental dams.'
case 177: return	'Dick Cheney.'
case 178: return	'Dick fingers.'
case 179: return	'Dining with cardboard cutouts of the cast of “Friends.”'
case 180: return	'Doin’ it in the butt.'
case 181: return	'Doing the right thing.'
case 182: return	'Domino’s Oreo Dessert Pizza.'
case 183: return	'Dorito breath.'
case 184: return	'Double penetration.'
case 185: return	'Drinking alone.'
case 186: return	'Dropping a chandelier on your enemies and riding the rope up.'
case 187: return	'Dry heaving.'
case 188: return	'Dwarf tossing.'
case 189: return	'Dying of dysentery.'
case 190: return	'Dying.'
case 191: return	'Eating all of the cookies before the AIDS bake-sale.'
case 192: return	'Eating an albino.'
case 193: return	'Eating an entire snowman.'
case 194: return	'Eating the last known Bison.'
case 195: return	'Edible underpants.'
case 196: return	'Elderly Japanese men.'
case 197: return	'Elf cum.'
case 198: return	'Embryonic stem cells.'
case 199: return	'Emotions.'
case 200: return	'Enormous Scandinavian women.'
    }
}


bot.on('message', (message)=>{ 
    if(message.content.endsWith("?")){
        message.channel.send(randomMessage());
    }
});


bot.login(TOKEN);

